- docs/guides/index.mdx
- updated to final quickstart guide
> #1 Quickstart Guide

- docs/aboutstudio/features.mdx
Review and feedback on updated information for this page.
> update information on Features and Capabilities page

- docs/aboutstudio/livestream/livestream.mdx
Created Livestream information, please review for changes/additional information required. 😀
> add information for Livestream page

- docs/aboutstudio/upload/upload.mdx
Created Upload information, please review for changes/additional information required. 😀
> add information for Upload page in About Studio

- docs/aboutstudio/mint/mint.mdx
Created Mint information, please review for changes/additional information required. 😀
> add Mint page to About Studio page

- api-key.mdx
#38  api key updated to new format
> 38 api key update

- docs/aboutstudio/toc.js
- docs/references/support-references.mdx
- docs/references/terminology.md
moved deleted pages to support references
updated toc
> added terminology

- docs/guides/livestreaming/multistream.mdx
Leaving code examples as cURL for now, but need to update it with JavaScript examples in v2.
> update Multistream guide to fit guides template

- docs/guides/livestreaming/record.mdx
Updated the record stream guide.
> update record stream guide

- docs/guides/livestreaming/broadcasting.mdx
Update the broadcasting software guide.
> update broadcasting software guide

- docs/references/session/get-session.mdx
“Get retrieve a session” - json response is an illegal json (extra “)
>  json response is an illegal json (extra } )

- docs/toc.js
removed extraneous references index page left on main toc
> # 122 Fixed Welcome Navigation

- docs/guides/on-demand.mdx
Updated guide based on changes provided from issue #1136 from Livepeer.com repo
> updated On Demand Guide from isssue #1136

- docs/guides/livestreaming/webrtmp.mdx
Updated the guide template for Stream via WebRTMP
> updated the guide template for Stream via WebRTMP

- docs/references/vod/upload.mdx
As per [https://github.com/livepeer/studio/pull/1112](https://github.com/livepeer/studio/pull/1112)
> docs: On Demand - Added resumable uploads docs

- docs/guides/livestreaming/playback.mdx
Update the URL for building a video player tutorial.
https://discord.com/channels/423160867534929930/995011403536662602/1004823847486377994
> update link for building video player tutorial

- docs/guides/livestreaming/srt.mdx
- docs/guides/toc.js
SRT documentation was missing in the docs, added a page with information from previous docs about SRT
> add srt to docs

- docs/guides/mint-guides/build-a-video-nft-app.mdx
- docs/guides/mint-guides/mint-a-video-nft.mdx
Fix broken links for Mint a Video NFT and Build a Video NFT app in the guides directory
> fix broken links on guides/mint

- docs/04-guides/on-demand/01-upload-video-asset/02-api.mdx
- docs/04-guides/on-demand/02-update-video-asset/02-api.mdx
- docs/04-guides/on-demand/03-store-video-asset-on-ipfs/02-api.mdx
> 202 Rename Code Blocks to JavaScript

- docs/04-guides/on-demand/01-upload-video-asset/02-api.mdx
- docs/04-guides/on-demand/02-update-video-asset/_tabs.mdx
- src/components/CodeBlockTabs/index.tsx
- src/css/custom.css
> 200 Add resumable uploads

- docs/02-quickstart/index.mdx
> 183 Quickstart

- docs/04-guides/on-demand/01-upload-video-asset/02-api.mdx
Changed `data` to `body` in the api request
> Change data to body

- docs/04-guides/playback-a-video-stream.mdx
> 181 Playback a Video

- docs/04-guides/playback-a-video-stream.mdx
@victorges 
Base on discussion:
https://discord.com/channels/423160867534929930/1025115716044718242/1025135486756470794
> change value from false to none

- docs/02-quickstart/index.mdx
- docs/04-guides/on-demand/01-upload-video-asset/02-api.mdx
- docs/04-guides/on-demand/03-store-video-asset-on-ipfs/02-api.mdx
> docs: add livepeerjs reference

- docs/05-reference/api/update-asset.mdx
- docs/05-reference/api/update-stream.mdx
> docs: API reference access control policy 

- docs/04-guides/get-viewer-engagement/02-api.mdx
- docs/04-guides/get-viewer-engagement/_tabs.mdx
> docs: custom player metrics

- docs/05-reference/support-matrix.mdx
> docs: update support matrix

- docs/04-guides/on-demand/02-update-video-asset/02-api.mdx
link for upload video asset api.
> docs: fix dead link in upload video asset API

- docs/05-reference/api/create-stream.mdx
- package.json
- yarn.lock
> 258 api reference playback policy post create stream

- docs/04-guides/on-demand/01-upload-video-asset/02-api.mdx
- docs/05-reference/api/create-asset-with-url.mdx
> docs: updated create asset endpoint

- docs/04-guides/listen-for-webhooks/01-dashboard.mdx
- docs/04-guides/listen-for-webhooks/02-api.mdx
- docs/04-guides/listen-for-webhooks/_tabs.mdx
- docs/04-guides/listen-for-webhooks/index.mdx
- docs/05-reference/api/delete-webhook.mdx
- docs/05-reference/api/edit-webhook.mdx
- docs/05-reference/api/get-webhook.mdx
- docs/05-reference/api/get-webhooks.mdx
- sidebars.js
> 174 listen for webhooks
